### ISSUE TITLE
User ID in the Dataset1 is the same user in the DataSet2

### ISSUE THREAD

**Issue by yali2015** [wsdream/wsdream-dataset#1]
Hello
Now I need the location of the user, and  I need the Dataset 2 , but there are no location information in the dataset2 . dataset1 has the location .
so I want to know if the user id in the dataset2 the same user in the dataset1
I am looking forward to your reply.
Thanks!

**Comment by jimzhu** [comment]
Sorry, no location information is recorded for dataset#2.

**Comment by yali2015** [comment]
Thank you for your answer.
Now I am studing the QoS in the base station, so I need to know the location of the users, Is there any relationship between users in dataset1 and datdset2? or do you any suitable dataset for me ?
I will be very appreciate it.

**Comment by jimzhu** [comment]
We do not currently have this type of data. But I thought the following paper released their dataset before, which may be of your interest. You may check with the authors about the dataset, since the link is not accessible now. 
> [WWW'14] Temporal QoS-aware web service recommendation via non-negative tensor factorization

**Comment by yali2015** [comment]
Thank you very much!
I have read the paper that you have recommended. the link is not accessible now so I will contact with the author about the dataset ,If they have the location of users ,my problem will be solved.
I appreciate you again.

**Comment by jimzhu** [comment]
No problem!
