### ISSUE TITLE
How can I get the wsdream-dataset?

### ISSUE THREAD

**Issue by Rebecca1102** [wsdream/wsdream-dataset#2]
Hello,
I'd like to acquire the wsdream dataset. But the download address links("http://wsdream.github.io/dataset/wsdream_dataset1.html" and "http://wsdream.github.io/dataset/wsdream_dataset2.html") given aren't accessible and they all show "Not Found". So I wonder whether there are other ways to get the data?
Looking forward to your reply. Thank you!

**Comment by jimzhu** [comment]
Thanks for your interest. We are moving the host of the datasets, so the links are temporally down. Please check the following link to download the files:
https://ndownloader.figshare.com/files/6842493
https://ndownloader.figshare.com/files/6842460

**Comment by Rebecca1102** [comment]
That's very kind of you. Thank you very much!
